from __future__ import annotations

import time
from dataclasses import dataclass
from pathlib import Path
from typing import Optional

from lxml import etree

NS = {"p": "urn:pxml:v1"}
NS_URI = "urn:pxml:v1"


def q(tag: str) -> str:
    return f"{{{NS_URI}}}{tag}"


@dataclass(frozen=True)
class ScenarioSpec:
    name: str
    task_id: str
    task_type: str
    risk_hint: str
    request_text: str
    requested_outcome: str
    expected_selected_path: str
    expected_write_intent: bool
    expected_exit_code: int
    expected_impl_status: Optional[str]
    expect_verifier_lane_call: bool
    expect_implementer_calls: int
    seed_files: tuple[str, ...]
    max_duration_sec: float


def _text(tree: etree._ElementTree, expr: str) -> Optional[str]:
    values = tree.xpath(expr, namespaces=NS)
    if not values:
        return None
    first = values[0]
    if isinstance(first, etree._Element):
        text = first.text
    else:
        text = str(first)
    if text is None:
        return None
    normalized = text.strip()
    return normalized or None


def _write_task_intake(path: Path, spec: ScenarioSpec) -> None:
    root = etree.Element(q("pxml"), nsmap={None: NS_URI})

    meta = etree.SubElement(root, q("meta"))
    etree.SubElement(meta, q("doc_id")).text = f"doc_task_intake_{spec.name}"
    etree.SubElement(meta, q("doc_class")).text = "task_intake"
    etree.SubElement(meta, q("schema_version")).text = "1.0.0"
    etree.SubElement(meta, q("task_id")).text = spec.task_id
    etree.SubElement(meta, q("run_id")).text = f"run_smoke_{spec.name}"
    etree.SubElement(meta, q("sequence")).text = "1"
    etree.SubElement(meta, q("writer_agent")).text = "system"
    etree.SubElement(meta, q("created_at")).text = "2026-03-23T00:00:00Z"

    etree.SubElement(root, q("refs"))

    payload = etree.SubElement(root, q("payload"))
    etree.SubElement(payload, q("request_text")).text = spec.request_text
    etree.SubElement(payload, q("task_type")).text = spec.task_type
    etree.SubElement(payload, q("requested_outcome")).text = spec.requested_outcome
    constraints = etree.SubElement(payload, q("constraints"))
    etree.SubElement(constraints, q("item")).text = "Keep runtime deterministic."
    etree.SubElement(payload, q("risk_hint")).text = spec.risk_hint
    etree.SubElement(
        payload, q("acceptance_hint")
    ).text = "Smoke test intake generated by pytest."

    integrity = etree.SubElement(root, q("integrity"))
    etree.SubElement(integrity, q("content_sha256")).text = "1" * 64

    path.parent.mkdir(parents=True, exist_ok=True)
    tree = etree.ElementTree(root)
    tree.write(str(path), encoding="UTF-8", xml_declaration=True, pretty_print=True)


def _seed_workspace(workspace_root: Path, seed_files: tuple[str, ...]) -> None:
    workspace_root.mkdir(parents=True, exist_ok=True)
    for relative in seed_files:
        target = workspace_root.joinpath(*relative.split("/"))
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_text("# seeded by smoke test\n", encoding="utf-8")


def _latest_artifact(runtime_root: Path, task_id: str, suffix: str) -> Path:
    return runtime_root / "latest" / f"{task_id}_{suffix}.pxml"


def _trace_events(trace_path: Path) -> list[dict[str, Optional[str]]]:
    tree = etree.parse(str(trace_path))
    nodes = tree.xpath("/p:pxml/p:payload/p:events/p:event", namespaces=NS)
    events: list[dict[str, Optional[str]]] = []
    for node in nodes:
        node_tree = etree.ElementTree(node)
        events.append(
            {
                "event_type": _text(node_tree, "./p:event_type"),
                "actor": _text(node_tree, "./p:actor"),
                "verify_phase": _text(node_tree, "./p:verify_phase"),
                "reason_code": _text(node_tree, "./p:reason_code"),
            }
        )
    return events


def _count_events(
    events: list[dict[str, Optional[str]]],
    event_type: str,
    actor: Optional[str] = None,
    verify_phase: Optional[str] = None,
) -> int:
    count = 0
    for event in events:
        if event.get("event_type") != event_type:
            continue
        if actor is not None and event.get("actor") != actor:
            continue
        if verify_phase is not None and event.get("verify_phase") != verify_phase:
            continue
        count += 1
    return count


def _run_executor(
    run_python,
    intake_path: Path,
    task_id: str,
    runtime_root: Path,
    workspace_root: Path,
) -> tuple[object, float]:
    started = time.perf_counter()
    result = run_python(
        "scripts/task_executor.py",
        "--intake",
        intake_path,
        "--task-id",
        task_id,
        "--runtime-root",
        runtime_root,
        "--workspace-root",
        workspace_root,
        "--verify-policy",
        "never",
        "--skip-validate",
    )
    elapsed = time.perf_counter() - started
    return result, elapsed


def test_task_executor_smoke_matrix_io_and_call_appropriateness(
    tmp_path: Path,
    run_python,
) -> None:
    scenarios = [
        ScenarioSpec(
            name="direct_feature_apply",
            task_id="task_smoke_direct_feature_001",
            task_type="feature",
            risk_hint="medium",
            request_text="Add a small profile helper with bounded scope.",
            requested_outcome="Apply one direct feature patch.",
            expected_selected_path="direct",
            expected_write_intent=True,
            expected_exit_code=0,
            expected_impl_status="applied",
            expect_verifier_lane_call=False,
            expect_implementer_calls=1,
            seed_files=(),
            max_duration_sec=20.0,
        ),
        ScenarioSpec(
            name="planner_pre_ambiguous",
            task_id="task_smoke_planner_pre_001",
            task_type="refactor",
            risk_hint="medium",
            request_text="Refactor boundary behavior is unclear and needs planning.",
            requested_outcome="Resolve ambiguity before implementation.",
            expected_selected_path="planner_pre",
            expected_write_intent=True,
            expected_exit_code=0,
            expected_impl_status="applied",
            expect_verifier_lane_call=False,
            expect_implementer_calls=1,
            seed_files=("src/refactor_target.py",),
            max_duration_sec=22.0,
        ),
        ScenarioSpec(
            name="verifier_post_high_risk",
            task_id="task_smoke_verifier_post_high_001",
            task_type="bugfix",
            risk_hint="high",
            request_text="Patch high risk lock boundary with deterministic evidence.",
            requested_outcome="Apply localized patch after verifier-backed gating.",
            expected_selected_path="verifier_post",
            expected_write_intent=True,
            expected_exit_code=0,
            expected_impl_status="applied",
            expect_verifier_lane_call=True,
            expect_implementer_calls=1,
            seed_files=("src/target_bugfix.py",),
            max_duration_sec=30.0,
        ),
        ScenarioSpec(
            name="verifier_post_verify_need",
            task_id="task_smoke_verifier_post_001",
            task_type="bugfix",
            risk_hint="medium",
            request_text="Fix retry boundary and verify regression behavior.",
            requested_outcome="Verification evidence is required for acceptance.",
            expected_selected_path="verifier_post",
            expected_write_intent=True,
            expected_exit_code=0,
            expected_impl_status="applied",
            expect_verifier_lane_call=True,
            expect_implementer_calls=1,
            seed_files=("src/target_bugfix.py",),
            max_duration_sec=30.0,
        ),
        ScenarioSpec(
            name="full_lane_critical",
            task_id="task_smoke_full_lane_001",
            task_type="refactor",
            risk_hint="critical",
            request_text="Critical auth boundary update with strict controls.",
            requested_outcome="Planner and verifier lanes all execute.",
            expected_selected_path="full_lane",
            expected_write_intent=True,
            expected_exit_code=0,
            expected_impl_status="applied",
            expect_verifier_lane_call=True,
            expect_implementer_calls=1,
            seed_files=("src/refactor_target.py",),
            max_duration_sec=30.0,
        ),
        ScenarioSpec(
            name="explore_only_read_only",
            task_id="task_smoke_explore_only_001",
            task_type="feature",
            risk_hint="medium",
            request_text="Read-only exploration only; do not modify code.",
            requested_outcome="Analysis only report without edits.",
            expected_selected_path="direct",
            expected_write_intent=False,
            expected_exit_code=0,
            expected_impl_status=None,
            expect_verifier_lane_call=False,
            expect_implementer_calls=0,
            seed_files=(),
            max_duration_sec=18.0,
        ),
    ]

    durations: dict[str, float] = {}

    for spec in scenarios:
        runtime_root = tmp_path / "runtime" / spec.name
        workspace_root = tmp_path / "workspace" / spec.name
        intake_path = tmp_path / "intake" / f"{spec.task_id}.pxml"

        _seed_workspace(workspace_root, spec.seed_files)
        _write_task_intake(intake_path, spec)

        result, elapsed = _run_executor(
            run_python=run_python,
            intake_path=intake_path,
            task_id=spec.task_id,
            runtime_root=runtime_root,
            workspace_root=workspace_root,
        )
        durations[spec.name] = elapsed

        assert result.returncode == spec.expected_exit_code, (
            result.stdout + result.stderr
        )
        assert elapsed < spec.max_duration_sec

        route_path = _latest_artifact(runtime_root, spec.task_id, "manager_route")
        packet_path = _latest_artifact(runtime_root, spec.task_id, "execution_packet")
        trace_path = _latest_artifact(runtime_root, spec.task_id, "execution_trace")
        exploration_path = _latest_artifact(
            runtime_root, spec.task_id, "exploration_result"
        )
        impl_path = _latest_artifact(runtime_root, spec.task_id, "implementer_result")

        assert route_path.exists(), f"missing manager_route for {spec.name}"
        assert packet_path.exists(), f"missing execution_packet for {spec.name}"
        assert trace_path.exists(), f"missing execution_trace for {spec.name}"

        route_tree = etree.parse(str(route_path))
        packet_tree = etree.parse(str(packet_path))

        selected_path = _text(route_tree, "/p:pxml/p:payload/p:selected_path")
        assert selected_path == spec.expected_selected_path
        lane_flag_nodes = route_tree.xpath(
            "/p:pxml/p:payload/p:lane_flags/*",
            namespaces=NS,
        )
        assert len(lane_flag_nodes) == 2

        write_intent_text = _text(packet_tree, "/p:pxml/p:payload/p:write_intent")
        write_intent = (
            True if write_intent_text is None else write_intent_text == "true"
        )
        assert write_intent == spec.expected_write_intent

        if spec.expected_impl_status is None:
            assert not impl_path.exists(), (
                f"unexpected implementer_result for {spec.name}"
            )
            assert exploration_path.exists(), (
                f"missing exploration_result for {spec.name}"
            )
        else:
            assert impl_path.exists(), f"missing implementer_result for {spec.name}"
            assert not exploration_path.exists(), (
                f"unexpected exploration_result for {spec.name}"
            )
            impl_tree = etree.parse(str(impl_path))
            impl_status = _text(impl_tree, "/p:pxml/p:payload/p:result_status")
            assert impl_status == spec.expected_impl_status

        events = _trace_events(trace_path)
        assert _count_events(events, "route") == 1
        assert _count_events(events, "packet_issued") == 1
        assert (
            _count_events(events, "implement_start", actor="implementer")
            == spec.expect_implementer_calls
        )
        assert _count_events(
            events,
            "verify_done",
            actor="verifier",
            verify_phase="lane",
        ) == (1 if spec.expect_verifier_lane_call else 0)
        assert _count_events(events, "explore_start", actor="explorer") == (
            0 if spec.expected_write_intent else 1
        )
        assert _count_events(events, "explore_done", actor="explorer") == (
            0 if spec.expected_write_intent else 1
        )

        expected_patch_applied = 1 if spec.expected_impl_status == "applied" else 0
        assert (
            _count_events(events, "patch_applied", actor="implementer")
            == expected_patch_applied
        )
        assert _count_events(events, "escalation") == 0

        verification_path = _latest_artifact(
            runtime_root, spec.task_id, "verification_result"
        )
        if spec.expect_verifier_lane_call:
            assert verification_path.exists(), (
                f"missing verification_result for {spec.name}"
            )
        else:
            assert not verification_path.exists(), (
                f"unexpected verification_result for {spec.name}"
            )

    direct_time = durations["direct_feature_apply"]
    explore_time = durations["explore_only_read_only"]
    full_lane_time = durations["full_lane_critical"]

    assert explore_time <= (direct_time * 2.0 + 2.0)
    assert full_lane_time <= (direct_time * 6.0 + 8.0)


def test_blocked_retry_failed_transition_and_call_counts(
    tmp_path: Path,
    run_python,
) -> None:
    task_id = "task_smoke_retry_failed_001"
    runtime_root = tmp_path / "runtime_retry"
    workspace_root = tmp_path / "workspace_retry"
    intake_path = tmp_path / "intake_retry" / f"{task_id}.pxml"

    spec = ScenarioSpec(
        name="retry_failed_path",
        task_id=task_id,
        task_type="bugfix",
        risk_hint="medium",
        request_text="Apply constrained bugfix patch with strict packet conformance.",
        requested_outcome="Repeated blocked cause should become retry_failed.",
        expected_selected_path="direct",
        expected_write_intent=True,
        expected_exit_code=1,
        expected_impl_status="blocked",
        expect_verifier_lane_call=False,
        expect_implementer_calls=1,
        seed_files=(),
        max_duration_sec=20.0,
    )

    _seed_workspace(workspace_root, spec.seed_files)
    _write_task_intake(intake_path, spec)

    first_result, first_elapsed = _run_executor(
        run_python=run_python,
        intake_path=intake_path,
        task_id=task_id,
        runtime_root=runtime_root,
        workspace_root=workspace_root,
    )
    assert first_result.returncode == 1, first_result.stdout + first_result.stderr
    assert first_elapsed < 20.0

    first_impl_path = _latest_artifact(runtime_root, task_id, "implementer_result")
    first_trace_path = _latest_artifact(runtime_root, task_id, "execution_trace")
    assert first_impl_path.exists()
    assert first_trace_path.exists()

    first_impl_tree = etree.parse(str(first_impl_path))
    first_status = _text(first_impl_tree, "/p:pxml/p:payload/p:result_status")
    first_reason = _text(first_impl_tree, "/p:pxml/p:payload/p:blocked_reason")
    assert first_status == "blocked"
    assert first_reason == "implementer_modify_target_missing"

    first_events = _trace_events(first_trace_path)
    assert _count_events(first_events, "implement_start", actor="implementer") == 1
    assert _count_events(first_events, "blocked", actor="implementer") == 1
    assert _count_events(first_events, "retry_failed", actor="implementer") == 0
    assert (
        _count_events(
            first_events,
            "verify_done",
            actor="verifier",
            verify_phase="lane",
        )
        == 0
    )

    second_result, second_elapsed = _run_executor(
        run_python=run_python,
        intake_path=intake_path,
        task_id=task_id,
        runtime_root=runtime_root,
        workspace_root=workspace_root,
    )
    assert second_result.returncode == 1, second_result.stdout + second_result.stderr
    assert second_elapsed < 20.0

    second_impl_path = _latest_artifact(runtime_root, task_id, "implementer_result")
    second_trace_path = _latest_artifact(runtime_root, task_id, "execution_trace")
    second_impl_tree = etree.parse(str(second_impl_path))
    second_status = _text(second_impl_tree, "/p:pxml/p:payload/p:result_status")
    second_reason = _text(second_impl_tree, "/p:pxml/p:payload/p:blocked_reason")
    retry_count_text = _text(second_impl_tree, "/p:pxml/p:payload/p:retry_count")
    escalation_requested = _text(
        second_impl_tree,
        "/p:pxml/p:payload/p:escalation_requested",
    )

    assert second_status == "retry_failed"
    assert second_reason == "implementer_modify_target_missing"
    assert retry_count_text is not None and int(retry_count_text) >= 2
    assert escalation_requested == "true"

    second_events = _trace_events(second_trace_path)
    assert _count_events(second_events, "implement_start", actor="implementer") == 2
    assert _count_events(second_events, "blocked", actor="implementer") >= 2
    assert _count_events(second_events, "retry_failed", actor="implementer") == 1
    assert _count_events(second_events, "escalation") >= 1
    assert _count_events(second_events, "stop") >= 1
    assert (
        _count_events(
            second_events,
            "verify_done",
            actor="verifier",
            verify_phase="lane",
        )
        == 0
    )
